### ISSUE TITLE
Práctica 6 de hilos en consola reporte.

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/practica-de-hilos-Arnold-Js#2]
[ReportePractica 6.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Arnold-Js/files/8520068/ReportePractica.6.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
